
import type { Edge, Node } from "@xyflow/react";
import type { AgenticNodeData } from "@/types/nodes";
import { TEMPLATE_TIER_FAST, TEMPLATE_TIER_BALANCED } from "@/lib/modelTiers";

export const AE_OPS_ROUTING_TEMPLATE: { nodes: Node[]; edges: Edge[] } = {
  edges: [
    { id: "e_1_2", source: "node_1", target: "node_2" },
    { id: "e_2_3", source: "node_2", target: "node_3" },
    { id: "e_3_4", source: "node_3", target: "node_4" },
    {
      id: "e_4_7",
      label: "Yes",
      style: { stroke: "#22c55e", strokeWidth: 2 },
      source: "node_4",
      target: "node_7",
      animated: true,
      sourceHandle: "true",
    },
    {
      id: "e_4_5",
      label: "No",
      style: { stroke: "#ef4444", strokeWidth: 2 },
      source: "node_4",
      target: "node_5",
      animated: true,
      sourceHandle: "false",
    },
    {
      id: "e_5_8",
      label: "Yes",
      style: { stroke: "#22c55e", strokeWidth: 2 },
      source: "node_5",
      target: "node_8",
      animated: true,
      sourceHandle: "true",
    },
    {
      id: "e_5_6",
      label: "No",
      style: { stroke: "#ef4444", strokeWidth: 2 },
      source: "node_5",
      target: "node_6",
      animated: true,
      sourceHandle: "false",
    },
    {
      id: "e_6_9",
      label: "Yes",
      style: { stroke: "#22c55e", strokeWidth: 2 },
      source: "node_6",
      target: "node_9",
      animated: true,
      sourceHandle: "true",
    },
    {
      id: "e_6_10",
      label: "No",
      style: { stroke: "#ef4444", strokeWidth: 2 },
      source: "node_6",
      target: "node_10",
      animated: true,
      sourceHandle: "false",
    },
    { id: "e_7_16", source: "node_7", target: "node_16" },
    { id: "e_16_12", source: "node_16", target: "node_12" },
    { id: "e_8_17", source: "node_8", target: "node_17" },
    { id: "e_17_11", source: "node_17", target: "node_11" },
    { id: "e_11_13", source: "node_11", target: "node_13" },
    { id: "e_9_18", source: "node_9", target: "node_18" },
    { id: "e_18_14", source: "node_18", target: "node_14" },
    { id: "e_10_19", source: "node_10", target: "node_19" },
    { id: "e_19_15", source: "node_19", target: "node_15" },
  ],
  nodes: [
    {
      id: "node_1",
      data: {
        label: "Webhook Trigger",
        config: {
          icon: "webhook",
          path: "/ae/ops/inbound",
          method: "POST",
        },
        status: "idle",
        displayName: "Ops intake (webhook or Studio)",
        nodeCategory: "trigger",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: -66, y: 264 },
    },
    {
      id: "node_2",
      data: {
        label: "Load Conversation State",
        config: {
          icon: "history",
          sessionIdExpression: "trigger.session_id",
        },
        status: "idle",
        displayName: "Load session history",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 220, y: 260 },
    },
    {
      id: "node_3",
      data: {
        label: "LLM Router",
        config: {
          icon: "route",
          ...TEMPLATE_TIER_FAST,
          intents: [
            "ops_orchestrator",
            "diagnostics",
            "remediation",
            "rca_report",
          ],
          historyNodeId: "node_2",
          userMessageExpression: "trigger.message",
        },
        status: "idle",
        displayName: "Route message to specialist",
        nodeCategory: "agent",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 460, y: 260 },
    },
    {
      id: "node_4",
      data: {
        label: "Condition",
        config: {
          icon: "git-branch",
          condition: 'node_3.intent == "diagnostics"',
          trueLabel: "Diagnostics",
          falseLabel: "Next",
        },
        status: "idle",
        displayName: "If intent = diagnostics",
        nodeCategory: "logic",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 700, y: 260 },
    },
    {
      id: "node_5",
      data: {
        label: "Condition",
        config: {
          icon: "git-branch",
          condition: 'node_3.intent == "remediation"',
          trueLabel: "Remediation",
          falseLabel: "Next",
        },
        status: "idle",
        displayName: "Else if intent = remediation",
        nodeCategory: "logic",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 940, y: 360 },
    },
    {
      id: "node_6",
      data: {
        label: "Condition",
        config: {
          icon: "git-branch",
          condition: 'node_3.intent == "rca_report"',
          trueLabel: "RCA",
          falseLabel: "Ops default",
        },
        status: "idle",
        displayName: "Else if intent = RCA report",
        nodeCategory: "logic",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1180, y: 460 },
    },
    {
      id: "node_7",
      data: {
        label: "ReAct Agent",
        config: {
          icon: "repeat",
          ...TEMPLATE_TIER_FAST,
          tools: ["ae.workflow.list", "ae.agent.list_running", "ae.request.get_status", "ae.request.get_logs", "ae.support.diagnose_failed_request"],
          systemPrompt:
            "You are the Diagnostic Specialist. Investigate RPA/workflow failures: pull status, logs, dependencies, files. Prefer MCP tools for status, logs, and diagnostics. Summarize evidence before suggesting fixes.",
          maxIterations: 12,
        },
        status: "idle",
        displayName: "Diagnostics specialist (ReAct + tools)",
        nodeCategory: "agent",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 980, y: 80 },
    },
    {
      id: "node_8",
      data: {
        label: "ReAct Agent",
        config: {
          icon: "repeat",
          ...TEMPLATE_TIER_FAST,
          tools: ["ae.request.restart", "ae.request.terminate_running", "ae.workflow.enable", "ae.ticket.create"],
          systemPrompt:
            "You are the Remediation Specialist. Execute corrective actions: restart workflows, notifications, safe config changes. Use MCP remediation/notification tools when available. Confirm impact before destructive steps.",
          maxIterations: 12,
        },
        status: "idle",
        displayName: "Remediation specialist (ReAct + tools)",
        nodeCategory: "agent",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1180, y: 220 },
    },
    {
      id: "node_9",
      data: {
        label: "LLM Agent",
        config: {
          icon: "brain",
          ...TEMPLATE_TIER_BALANCED,
          temperature: 0.35,
          systemPrompt:
            "You are the RCA Specialist. Produce a structured incident report: Summary, Timeline, Root cause, Impact, Prevention. Use conversation and prior node outputs in context.",
        },
        status: "idle",
        displayName: "RCA report author",
        nodeCategory: "agent",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1420, y: 400 },
    },
    {
      id: "node_10",
      data: {
        label: "ReAct Agent",
        config: {
          icon: "repeat",
          ...TEMPLATE_TIER_FAST,
          tools: ["ae.workflow.list", "ae.agent.list_running", "ae.request.list_recent", "ae.schedule.list_all", "ae.support.diagnose_failed_request"],
          systemPrompt:
            "You are the Ops Orchestrator. Default handler for AutomationEdge ops: workflows, queues, schedules, agents, batch jobs. When a user asks for a 'list of workflows', 'list of agents', or 'list of schedules', call the appropriate tool (ae.workflow.list, ae.agent.list_running, ae.schedule.list_all) IMMEDIATELY and show the results. Do not ask for clarification if the request is clearly for a resource list. Summarize the results clearly for the user.",
          maxIterations: 10,
        },
        status: "idle",
        displayName: "Default ops orchestrator (ReAct)",
        nodeCategory: "agent",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1420, y: 560 },
    },
    {
      id: "node_11",
      data: {
        label: "Human Approval",
        config: {
          icon: "user-check",
          timeout: 86400,
          approvalMessage:
            "Approve remediation actions before they are persisted to conversation history.",
        },
        status: "idle",
        displayName: "Human gate: approve remediation",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1606, y: 221 },
    },
    {
      id: "node_12",
      data: {
        label: "Save Conversation State",
        config: {
          icon: "save",
          responseNodeId: "node_7",
          sessionIdExpression: "trigger.session_id",
          userMessageExpression: "trigger.message",
        },
        status: "idle",
        displayName: "Save turn · diagnostics answer",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1680, y: 80 },
    },
    {
      id: "node_13",
      data: {
        label: "Save Conversation State",
        config: {
          icon: "save",
          responseNodeId: "node_8",
          sessionIdExpression: "trigger.session_id",
          userMessageExpression: "trigger.message",
        },
        status: "idle",
        displayName: "Save turn · remediation (after approval)",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1903, y: 221 },
    },
    {
      id: "node_14",
      data: {
        label: "Save Conversation State",
        config: {
          icon: "save",
          responseNodeId: "node_9",
          sessionIdExpression: "trigger.session_id",
          userMessageExpression: "trigger.message",
        },
        status: "idle",
        displayName: "Save turn · RCA answer",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 2082, y: 396 },
    },
    {
      id: "node_15",
      data: {
        label: "Save Conversation State",
        config: {
          icon: "save",
          responseNodeId: "node_10",
          sessionIdExpression: "trigger.session_id",
          userMessageExpression: "trigger.message",
        },
        status: "idle",
        displayName: "Save turn · default ops answer",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 2108, y: 552 },
    },
    {
      id: "node_16",
      data: {
        label: "Bridge User Reply",
        config: {
          icon: "message-square",
          responseNodeId: "node_7",
          messageExpression: "",
        },
        status: "idle",
        displayName: "Chat reply · diagnostics",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1320, y: 80 },
    },
    {
      id: "node_17",
      data: {
        label: "Bridge User Reply",
        config: {
          icon: "message-square",
          responseNodeId: "node_8",
          messageExpression: "",
        },
        status: "idle",
        displayName: "Chat reply · remediation",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1280, y: 220 },
    },
    {
      id: "node_18",
      data: {
        label: "Bridge User Reply",
        config: {
          icon: "message-square",
          responseNodeId: "node_9",
          messageExpression: "",
        },
        status: "idle",
        displayName: "Chat reply · RCA",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1754, y: 402 },
    },
    {
      id: "node_19",
      data: {
        label: "Bridge User Reply",
        config: {
          icon: "message-square",
          responseNodeId: "node_10",
          messageExpression: "",
        },
        status: "idle",
        displayName: "Chat reply · default ops",
        nodeCategory: "action",
      } satisfies AgenticNodeData,
      type: "agenticNode",
      position: { x: 1758, y: 562 },
    },
  ],
};
